### ISSUE TITLE
Use an extra feature such as e.g. synchronizer

### ISSUE THREAD

**Issue by tamaramagdr** [danvk/dygraphs-es6#1]
I have a rather large React application using Webpack to bundle it for production and would like to synchronize multiple graphs. 

To make sure I did not make mistakes elsewhere in my application (although I'm sure there are still plenty) I cloned this repo, added another graph to index.js and tried to use the synchronize function. 

    import Dygraph from 'dygraphs';

    // or, if you don't want to use ES6 imports:
    // const Dygraph = require('dygraphs');

    const g = new Dygraph('graph',
    `Date,A,B
    2016/01/01,10,20
    2016/07/01,20,10
    2016/12/31,40,30
    `, {
      fillGraph: true
    });

    const h = new Dygraph('graph',
    `Date,A,B
    2016/01/01,10,20
    2016/07/01,20,10
    2016/12/31,40,30
    `, {
      fillGraph: true
    });

    Dygraph.synchronize(g, h);

As expected, I got the same error: `TypeError: _dygraphs2.default.synchronize is not a function`

What am I doing wrong? I tried everything I could think of to explicitly source the synchronizer and don't really know what to try anymore. 

I'm happy for any hint or idea what to try to make that work. Thanks in advance!

**Comment by ikmolbo** [comment]
Did you manage to solve this problem? I'm having exactly the same trouble...

**Comment by tamaramagdr** [comment]
Since this was a while ago, I hope I don't forget to mention anything. My apologies if I do.

As far as I remember we simply copied the synchronizer.js file (and other extras we needed) into our app directory and slightly modified it to suit our needs (imported Dygraph at the beginning, exported the synchronize function and removed the last three lines):

    import Dygraph from 'dygraphs';

    export function synchronize (/* dygraphs..., opts */) {
	    if (arguments.length === 0) {
        
        ....

    }

Then, you can simply import the synchronize function from that file and use it.

This workaround worked well, yet I'd still hope that there might be a neater way than copying and pasting entire files into our app. I'm sorry I can't be of more help.

**Comment by ikmolbo** [comment]
Hello,

That’s really helpful, thank you. 

Just to spell it out, then, you imported the copied synchronised function as follows:

import ‘path/to/synchronized/copy’

Or should it be (for example):

import Synchronize from ‘path/to/synchronized/copy’

?

Do you think you could paste the entire file as you modified it?

Thanks again!

**Comment by tamaramagdr** [comment]
I think I imported the synchronize function explicitly as `import {synchronize} from path/to/synchronized/copy` and then just used it as such.
I don't have access to the modified file right this moment, but I can check tomorrow and post it here.

**Comment by tamaramagdr** [comment]
Hi, so I double checked, I imported it as `import {synchronize} from /path/to/synchronization`. Attached you can find the modified file. Hope that helps.
[synchronization.js.zip](https://github.com/danvk/dygraphs-es6/files/1655393/synchronization.js.zip)

**Comment by ikmolbo** [comment]
That’s very kind of you, thank you very much!

**Comment by tamaramagdr** [comment]
Not a problem :)

**Comment by angelasuamo** [comment]
Hi! Could you tell me how I can modify the file synchronize.js to react, I am using the file that appears in this forum and it gives me an error saying that g.ready is not function, could you help me please, thanks

**Comment by hakim89** [comment]
@tamaramagdr your file worked in SvelteKit out of the box. Thank you
